const jobsArray = [
    { title: "Dentist" },
    { title: "Registered Nurse" },
    { title: "Pharmacist" },
    { title: "Computer Systems Analyst" },
    { title: "Physician" },
    { title: "Database Administrator" },
    { title: "Software Developer" },
    { title: "Physical Therapist" },
    { title: "Web Developer" },
    { title: "Dental Hygienist" },
    { title: "Occupational Therapist" },
    { title: "Veterinarian" },
    { title: "Computer Programmer" },
    { title: "School Psychologist" },
    { title: "Physical Therapist Assistant" },
    { title: "Interpreter & Translator" },
    { title: "Mechanical Engineer" },
    { title: "Veterinary Technologist & Technician" },
    { title: "Epidemiologist" },
    { title: "IT Manager" },
    { title: "Market Research Analyst" },
    { title: "Diagnostic Medical Sonographer" },
    { title: "Computer Systems Administrator" },
    { title: "Respiratory Therapist" },
    { title: "Medical Secretary" },
    { title: "Civil Engineer" },
    { title: "Substance Abuse Counselor" },
    { title: "Speech-Language Pathologist" },
    { title: "Landscaper & Groundskeeper" },
    { title: "Radiologic Technologist" },
    { title: "Cost Estimator" },
    { title: "Financial Advisor" },
    { title: "Marriage & Family Therapist" },
    { title: "Medical Assistant" },
    { title: "Lawyer" },
    { title: "Accountant" },
    { title: "Compliance Officer" },
    { title: "High School Teacher" },
    { title: "Clinical Laboratory Technician" },
    { title: "Maintenance & Repair Worker" },
    { title: "Bookkeeping, Accounting, & Audit Clerk" },
    { title: "Financial Manager" },
    { title: "Recreation & Fitness Worker" },
    { title: "Insurance Agent" },
    { title: "Elementary School Teacher" },
    { title: "Dental Assistant" },
    { title: "Management Analyst" },
    { title: "Home Health Aide" },
    { title: "Pharmacy Technician" },
    { title: "Construction Manager" },
];

module.exports = { jobsArray };  